Update simple.yml

diff --git a/.github/workflows/simple.yml b/.github/workflows/simple.yml
--- a/.github/workflows/simple.yml
+++ b/.github/workflows/simple.yml
@@ -26,8 +26,11 @@ jobs:
       - uses: actions/checkout@v2
 
       # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run:  |
-          echo Hello, World > log.txt
-          sleep 10
-          echo Hello again >> log.txt
+      - name: Check if main.cpp exists
+        run: |
+          if [ -f "main.cpp" ]; then
+            echo "main.cpp found."
+          else
+            echo "Error: main.cpp not found." >&2
+            exit 1
+          fi
